# Generated by Django 4.1.1 on 2022-09-30 12:56

from django.db import migrations
from github import Github
from zoneinfo import ZoneInfo


def load_initial_data(apps, schema_editor):
    g = Github()
    repo = g.get_user('nebracy').get_repo('django-portfolio-website')
    Commit = apps.get_model('home', 'Commit')

    commits = [
        Commit(
            commit_id=c.commit.sha,
            name=repo.name,
            url=repo.html_url,
            date=c.commit.committer.date.replace(tzinfo=ZoneInfo('UTC')),
            msg=c.commit.message)
        for c in repo.get_commits()[:4]
    ]

    Commit.objects.bulk_create(commits)


def delete_all_data(apps, schema_editor):
    Commit = apps.get_model('home', 'Commit')
    Commit.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, delete_all_data)
    ]
